default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: remba_development

test:
  <<: *default
  database: remba_test

production:
  <<: *default
  database: remba_production
  username: remba
  password: <%= ENV['REMBA_DATABASE_PASSWORD'] %>
